name: 'Install zkstack'

description: 'Builds or downloads zkstack.'

runs:
  using: "composite"
  steps:

    # TODO: return when merging to main
    # - name: Check zkstack changes
    #   id: changed-files
    #   uses: tj-actions/changed-files@v45
    #   with:
    #     files: |
    #       zkstack_cli/**

    - name: Download zkstack
      id: download-zkstack
      shell: 'bash -ex {0}'
      env:
        ZKSTACK_WORKFLOW_NAME: 'Build zkstack'
        GH_TOKEN: ${{ github.token }}
      working-directory: bin
      # if: ${{ steps.changed-files.outputs.any_changed == 'false' }}
      run: |
        for RUN in $(gh run list -R matter-labs/zksync-era --workflow "${ZKSTACK_WORKFLOW_NAME}" --status success --json databaseId --jq '.[].databaseId'); do
          if gh run download -R matter-labs/zksync-era "${RUN}" -n "zkstack-${{ runner.arch }}"; then
            echo "zkstack binary successfully downloaded. Skip rebuilding..."
            ./zkstack --version
            exit 0
          fi
        done
        echo "No prebuilt zkstack found. Rebuilding..."
        echo "rebuild-required=true" >> "${GITHUB_OUTPUT}"

    - name: Build zkstack
      shell: 'bash -ex {0}'
      if: ${{ steps.changed-files.outputs.any_changed == 'true' || steps.download-zkstack.outputs.rebuild-required == 'true' }}
      run: |
        ./zkstack_cli/zkstackup/zkstackup --local --cargo-features gateway
        echo "${HOME}/.local/bin" >> "${GITHUB_PATH}"
