name: Release-please

on:
  workflow_call:
    secrets:
      gh_token:
        description: 'GitHub token'
        required: true
      cargo_registry_token:
        description: 'Cargo registry token'
        required: false
      slack_webhook:
        description: 'Slack webhook for notifications'
        required: false
    inputs:
      manifest:
        type: string
        description: 'Path to release-please manifest file'
        required: true
      config:
        type: string
        description: 'Path to release-please configuration file'
        required: true
      run_build:
        type: boolean
        description: 'Build the workspace before release'
        required: false
        default: true
      run_tests:
        type: boolean
        description: 'Run tests before release'
        required: false
        default: false
      workspace-dirs:
        type: string
        description: 'Path to the workspace directories. To be used in configurations of release-please with merged PR for different components.'
        required: false
        default: '.'
      publish-to-crates-io:
        type: string
        description: 'Whether to publish to crates.io'
        required: false
        default: 'false'
      update-cargo-lock:
        type: string
        description: 'Whether to update Cargo.lock'
        required: false
        default: 'true'
      upgrade-dependencies:
        type: string
        description: 'Whether to upgrade dependencies'
        required: false
        default: 'false'
      org-owner:
        type: string
        description: 'Organization to add as owner of the crates.'
        required: false
        default: 'github:matter-labs:crates-io'
      git-user-name:
        type: string
        description: 'Name of the user to use for git operations.'
        required: false
        default: 'zksync-era-bot'
      git-user-email:
        type: string
        description: 'Email of the user to use for git operations.'
        required: false
        default: 'zksync-era-bot@users.noreply.github.com'
      cargo-lock-commit-message:
        type: string
        description: 'Commit message for Cargo.lock update.'
        required: false
        default: 'chore: update Cargo.lock'

jobs:

  release-please:
    runs-on: ubuntu-latest
    outputs:
      prs_created: ${{ steps.release.outputs.prs_created }}
      releases_created: ${{ steps.release.outputs.releases_created }}
      releases: ${{ steps.release.outputs.releases }}
      prs: ${{ steps.release.outputs.prs }}
      paths_released: ${{ steps.release.outputs.paths_released }}
    steps:

      - name: Run release-please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.gh_token }}
          config-file: ${{ inputs.config }}
          manifest-file: ${{ inputs.manifest }}

      - name: Slack notification
        if: failure()
        uses: matter-labs/zksync-ci-common/.github/actions/slack-notify-release@aba-release-please-support
        with:
          webhook: ${{ secrets.slack_webhook }}
          context: 'Unable execute release-please'


  update-cargo-lock:
    name: Update Cargo.lock
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.prs_created == 'true' && inputs.update-cargo-lock  == 'true' }}
    strategy:
      matrix:
        pr_branch: ${{ fromJson(needs.release-please.outputs.prs).*.headBranchName }}
      fail-fast: false
      max-parallel: 1
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.pr_branch }}
          token: ${{ secrets.gh_token }}
          submodules: "recursive"

      # It will automatically check for rust-toolchain file in the repository
      # and take care of the proper caching to speed up CI.
      - name: Install Rust toolchain
        uses: moonrepo/setup-rust@v1

      - name: Update Cargo.lock
        shell: 'bash -ex {0}'
        run: |
          BRANCH="${{ matrix.pr_branch }}"
          if [[ ${BRANCH} == *components* ]]; then
            COMPONENT="${BRANCH##*--}"
            ( cd "${COMPONENT}" && cargo update --workspace )
          else
            for WORKSPACE in ${{ inputs.workspace-dirs }} ; do
              ( cd "${WORKSPACE}" && cargo update --workspace )
            done
          fi
          if ! git diff --exit-code --quiet; then
            git config user.name "${{ inputs.git-user-name }}"
            git config user.email "${{ inputs.git-user-email }}"
            git add .
            git commit -m "${{ inputs.cargo-lock-commit-message }}"
            git push --set-upstream origin ${{ matrix.pr_branch }}
          fi

      - name: Slack notification
        if: failure()
        uses: matter-labs/zksync-ci-common/.github/actions/slack-notify-release@aba-release-please-support
        with:
          webhook: ${{ secrets.slack_webhook }}
          context: 'Unable to update Cargo.lock'


  publish-crates:
    needs: release-please
    name: Publish to crates.io
    runs-on: ubuntu-latest
    if: ${{ needs.release-please.outputs.releases_created == 'true' && inputs.publish-to-crates-io == 'true' }}
    strategy:
      matrix:
        path: ${{ fromJson(needs.release-please.outputs.paths_released) }}
      fail-fast: false
      max-parallel: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.gh_token }}
          submodules: "recursive"

      # It will automatically check for rust-toolchain file in the repository
      # and take care of the proper caching to speed up CI.
      - name: Install Rust toolchain
        uses: moonrepo/setup-rust@v1
        with:
          bins: 'cargo-workspaces'

      - name: Build the workspace before release
        shell: 'bash -ex {0}'
        if: ${{ inputs.run_build == true || inputs.run_build == 'true' }}
        working-directory: ${{ matrix.path }}
        run: cargo build

      - name: Run tests before release
        shell: 'bash -ex {0}'
        if: ${{ inputs.run_tests == true || inputs.run_tests == 'true' }}
        working-directory: ${{ matrix.path }}
        run: cargo test

      - name: Release packages to crates.io
        shell: 'bash -ex {0}'
        working-directory: ${{ matrix.path }}
        run: |
          cargo login ${{ secrets.cargo_registry_token }}
          cargo workspaces publish --from-git

      - name: Update ownership
        shell: 'bash -ex {0}'
        if: success() && inputs.org-owner != ''
        working-directory: ${{ matrix.path }}
        run: |
          ORG_OWNER=${{ inputs.org-owner }}
          cargo login ${{ secrets.cargo_registry_token }}
          for PKG in $(cargo ws list); do
            cargo owner --list --quiet ${PKG} | grep ${ORG_OWNER} || cargo owner --add ${ORG_OWNER} ${PKG}
          done

      - name: Slack notification
        if: failure()
        uses: matter-labs/zksync-ci-common/.github/actions/slack-notify-release@aba-release-please-support
        with:
          webhook: ${{ secrets.slack_webhook }}
          context: 'Unable to publish to crates.io'


  upgrade-published-dependencies:
    needs: [release-please, publish-crates]
    name: Upgrade dependencies
    runs-on: ubuntu-latest
    if: ${{ needs.release-please.outputs.releases_created == 'true' && inputs.upgrade-dependencies == 'true' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.repository.default_branch }}
          token: ${{ secrets.gh_token }}
          submodules: "recursive"

      # It will automatically check for rust-toolchain file in the repository
      # and take care of the proper caching to speed up CI.
      - name: Install Rust toolchain
        uses: moonrepo/setup-rust@v1
        with:
          bins: 'cargo-workspaces,cargo-edit'

      - name: Upgrade packages
        shell: 'bash -ex {0}'
        run: |
          set -o pipefail
          for PATH_RELEASED in $(echo '${{ needs.release-please.outputs.paths_released }}' | jq -r '.[]'); do
            for COMPONENT in $(jq -r '.packages | keys[]' ${{ inputs.config }} ); do
              (
                MANIFEST=$(realpath "${PATH_RELEASED}/Cargo.toml")
                cd "${COMPONENT}"
                cargo metadata --manifest-path ${MANIFEST} \
                  --no-deps --format-version 1 | jq -r '.packages[] | "\(.name) \(.version)"' | while read -r PACKAGE VERSION; do
                    cargo upgrade --pinned -p ${PACKAGE}@${VERSION} || true
                done
              )
            done
          done

      - name: Commit changes
        shell: 'bash -ex {0}'
        env:
          GH_TOKEN: ${{ secrets.gh_token }}
        run: |
          BRANCH="upgrade-crates-io-dependencies-$(date +%s)"
          if ! git diff --exit-code --quiet; then
            git config user.name "${{ inputs.git-user-name }}"
            git config user.email "${{ inputs.git-user-email }}"
            git checkout -b ${BRANCH}
            git add .
            git commit -m "chore: upgrade crates.io dependencies"
            git push --set-upstream origin ${BRANCH}
            gh pr create --title "chore: upgrade crates.io dependencies" \
              --body "Upgrade workspace dependencies to the latest versions" \
              --base "${{ github.event.repository.default_branch }}" \
              --head "${BRANCH}"
          fi

      - name: Slack notification
        if: failure()
        uses: matter-labs/zksync-ci-common/.github/actions/slack-notify-release@aba-release-please-support
        with:
          webhook: ${{ secrets.slack_webhook }}
          context: 'Unable to upgrade cargo dependencies'
